### ISSUE TITLE
Scrolling no longer works after 0.17.0

### ISSUE THREAD

**Issue by mifi** [deanhet/react-native-text-ticker#56] opened 2019-10-08 23:37 UTC
Caused by this change:
https://github.com/deanhet/react-native-text-ticker/commit/eca4f78ddfba41b959e0ff3b8124e55de8e2e854

Every time I'm re-rendering the component (my whole subtree is re-rendered 3 times per second), it will reset and not move at all, even though the text remains the same. I think maybe it's better to find another way to compare props than props.children != prevProps.children

**Comment by deanhet** [comment] 2019-10-09 08:55
I'm trying to replicate your issue so I've written a small example:

```
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import TextTicker from 'react-native-text-ticker'

export default function App() {

  const [text, setText] = useState('This is a long string of text that should start scrolling across the page');

  useEffect(() => {
    setInterval(() => {
      setText(text + " & this should only reset once")
    }, 1000);
  }, [])
  return (
    <View style={styles.container}>
      <TextTicker>{text}</TextTicker>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

This will change the child on the first setInterval and reset the scroll as expected. However, next time the string is the same (children are still the same) and it doesn't cause the scroll to reset.

Perhaps the issue is an implementation issue? Would be happy to look at any examples you have.

**Comment by mifi** [comment] 2019-10-09 15:12
Ok turns out it was a bit more tricky to reproduce. I reproduced like this: 😅
```js
function Comp2() {
  const otherVal = useContext(TestContext);
  return <TextTicker duration={5000}>{'this causes reset every time.... long text blablabalbalbalblablalbalbal'}{'other'}</TextTicker>;
}

function Comp1() {
  const [otherVal, setOtherVal] = useState('');

  useEffect(() => {
    setInterval(() => {
      setOtherVal(`${new Date().getTime()}`);
    }, 300);
  }, []);

  return (
    <View style={styles.container}>
      <TestContext.Provider value={otherVal}>
        <Comp2 />
      </TestContext.Provider>
    </View>
  );
}
```
Note: otherVal doesnt matter if it's used or not. Just because we use context it will cause re-render.
Also we need `{'this causes reset every time.... long text blablabalbalbalblablalbalbal'}` AND `{'other'}` together in children. If only one, I guess react optimizes the re-render away

**Comment by mifi** [comment] 2019-10-09 15:15
If it's hard to fix, maybe can have a flag to disable this reset.

**Comment by deanhet** [comment] 2019-10-10 08:51
I think this is because you have multiple children, React isn't doing a deep compare on what the children are so doesn't know they're still the same.

Can you try putting your multiple children as a single string template instead? The below seems to work for me.

```
return <TextTicker duration={5000}>{`this causes reset every time.... long text blablabalbalbalblablalbalbal other ${anyOtherVariable}`}</TextTicker>;
```

**Comment by mifi** [comment] 2019-10-10 10:39
Yup that works just as well. What if the user wants to put different text styles inside the same ticker? Like `<TextTicker><Text style={{ fontWeight: 'bold' }}>some bold</Text> Some Normal text</TextTicker>`, or is this not supported?
If not supported, then we should put in the readme that only an single text string as children is supported.

**Comment by deanhet** [comment] 2019-10-10 10:44
You're right, with the current implementation that's not currently supported. Maybe in the future!

I'll close this issue for now and add a line to the readme. Thanks for working through this!

**Closed by deanhet** 2019-10-10 10:44 UTC
